/**
 * HTML post-processing utilities for export (ZEST-016).
 *
 * Business rules:
 *   BR-012 — inject meta charset + viewport tags
 *   BR-013 — output must NOT be minified (we never strip whitespace)
 */

const META_CHARSET = '<meta charset="UTF-8">';
const META_VIEWPORT = '<meta name="viewport" content="width=device-width, initial-scale=1">';
const WATERMARK = "<!-- Generated by Zest -->";

// ---------------------------------------------------------------------------
// injectMeta
// ---------------------------------------------------------------------------

/**
 * Ensure `<meta charset="UTF-8">` and `<meta name="viewport" ...>` are
 * present inside `<head>`. If they are already present, nothing changes.
 * If `<head>` is missing, a minimal `<head>` is prepended to the document.
 */
export function injectMeta(html: string): string {
  let result = html;

  // Insert into existing <head> if present
  if (/<head[^>]*>/i.test(result)) {
    // Add charset if missing
    if (!/<meta[^>]+charset/i.test(result)) {
      result = result.replace(/(<head[^>]*>)/i, `$1\n  ${META_CHARSET}`);
    }
    // Add viewport if missing
    if (!/<meta[^>]+viewport/i.test(result)) {
      result = result.replace(/(<head[^>]*>)/i, `$1\n  ${META_VIEWPORT}`);
    }
  } else {
    // No <head> — prepend a minimal one
    const headBlock = `<head>\n  ${META_CHARSET}\n  ${META_VIEWPORT}\n</head>\n`;
    if (/<html[^>]*>/i.test(result)) {
      result = result.replace(/(<html[^>]*>)/i, `$1\n${headBlock}`);
    } else {
      result = headBlock + result;
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// addWatermark
// ---------------------------------------------------------------------------

/**
 * Insert `<!-- Generated by Zest -->` immediately after the `<body>` tag.
 * If `<body>` is absent, append to end of document.
 */
export function addWatermark(html: string): string {
  if (html.includes(WATERMARK)) return html; // already present

  if (/<body[^>]*>/i.test(html)) {
    return html.replace(/(<body[^>]*>)/i, `$1\n${WATERMARK}`);
  }
  return html + `\n${WATERMARK}`;
}

// ---------------------------------------------------------------------------
// stripWatermark
// ---------------------------------------------------------------------------

/**
 * Remove the `<!-- Generated by Zest -->` watermark comment if present.
 */
export function stripWatermark(html: string): string {
  return html.replace(/\n?<!-- Generated by Zest -->/g, "");
}
